export default {
  IonDefaultAccessToken:
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIzZDA1MTcwOC1mMTRmLTRmYzAtYTg1OC1mNzljMWUxNjY4N2EiLCJpZCI6Njk3NzksImlhdCI6MTYzMzc0MjkyMX0.hERWhSXbymiaRYx8iedvoR5T2aZ5AP8jersCajn47IQ",
}